name: Update Brew Tap

on:
  release:
    types: released

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2

    - name: Update Homebrew Formula
      uses: izumin5210/action-homebrew-tap@v1.0.0
      with:
        tap: 'ddelange/brewformulae'
        token: '${{ secrets.GITHUB_TOKEN }}'
        tap-token: '${{ secrets.PUSH_TOKEN }}'

    - name: Test Homebrew Install
      run: brew install --ignore-dependencies ddelange/brewformulae/yt
