name: CD

on:
  release:
    types: [released]  # skip prereleased
  workflow_dispatch:  # allows running CI manually from the Actions tab

jobs:
  update_tap:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom GitHub access token with only the 'public_repo' scope
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          tap: ddelange/brewformulae
          livecheck: true
